name: Exemplo com Docker e JavaScript

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  run-docker-js:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # Contrói a imagem Docker
      - name: Construir imagem Docker
        run: docker build -t meu-node-app .

      # Executa o container e roda o script
      - name: Executar container
        run: docker run meu-node-app